// flow-typed signature: c3d27a0792d5c5b85003d2ef8982bc20
// flow-typed version: <<STUB>>/telegraf_v^3.3.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'telegraf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'telegraf' {
  declare type updateType =
    'callback_query' |
    'channel_post' |
    'chosen_inline_result' |
    'edited_channel_post' |
    'edited_message' |
    'inline_query' |
    'shipping_query' |
    'pre_checkout_query' |
    'message' |

    'voice' |
    'video_note' |
    'video' |
    'venue' |
    'text' |
    'supergroup_chat_created' |
    'successful_payment' |
    'sticker' |
    'pinned_message' |
    'photo' |
    'new_chat_title' |
    'new_chat_photo' |
    'new_chat_members' |
    'migrate_to_chat_id' |
    'migrate_from_chat_id' |
    'location' |
    'left_chat_member' |
    'invoice' |
    'group_chat_created' |
    'game' |
    'document' |
    'delete_chat_photo' |
    'contact' |
    'channel_chat_created' |
    'audio';

  declare class Telegraf {
    constructor: (token: string, options?: {
      telegram: {
        agent: http$Agent,
        webhookReply: boolean
      },
      username?: string
    }) => this;

    on: (updateTypes: updateType | updateType[], middleware: Function) => this;
    startPolling: (timeout?: number, limit?: number, allowedUpdates?: string[]) => this;
  }

  declare module.exports: typeof Telegraf;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'telegraf/lib/core/composer' {
  declare module.exports: any;
}

declare module 'telegraf/lib/core/context' {
  declare module.exports: any;
}

declare module 'telegraf/lib/core/router' {
  declare module.exports: any;
}

declare module 'telegraf/lib/core/session' {
  declare module.exports: any;
}

declare module 'telegraf/lib/helpers/extra' {
  declare module.exports: any;
}

declare module 'telegraf/lib/helpers/markup' {
  declare module.exports: any;
}

declare module 'telegraf/lib/helpers/replicators' {
  declare module.exports: any;
}

declare module 'telegraf/lib/index' {
  declare module.exports: any;
}

declare module 'telegraf/lib/network/client' {
  declare module.exports: any;
}

declare module 'telegraf/lib/network/error' {
  declare module.exports: any;
}

declare module 'telegraf/lib/network/multipart-stream' {
  declare module.exports: any;
}

declare module 'telegraf/lib/network/webhook' {
  declare module.exports: any;
}

declare module 'telegraf/lib/telegraf' {
  declare module.exports: any;
}

declare module 'telegraf/lib/telegram' {
  declare module.exports: any;
}

// Filename aliases
declare module 'telegraf/lib/core/composer.js' {
  declare module.exports: $Exports<'telegraf/lib/core/composer'>;
}
declare module 'telegraf/lib/core/context.js' {
  declare module.exports: $Exports<'telegraf/lib/core/context'>;
}
declare module 'telegraf/lib/core/router.js' {
  declare module.exports: $Exports<'telegraf/lib/core/router'>;
}
declare module 'telegraf/lib/core/session.js' {
  declare module.exports: $Exports<'telegraf/lib/core/session'>;
}
declare module 'telegraf/lib/helpers/extra.js' {
  declare module.exports: $Exports<'telegraf/lib/helpers/extra'>;
}
declare module 'telegraf/lib/helpers/markup.js' {
  declare module.exports: $Exports<'telegraf/lib/helpers/markup'>;
}
declare module 'telegraf/lib/helpers/replicators.js' {
  declare module.exports: $Exports<'telegraf/lib/helpers/replicators'>;
}
declare module 'telegraf/lib/index.js' {
  declare module.exports: $Exports<'telegraf/lib/index'>;
}
declare module 'telegraf/lib/network/client.js' {
  declare module.exports: $Exports<'telegraf/lib/network/client'>;
}
declare module 'telegraf/lib/network/error.js' {
  declare module.exports: $Exports<'telegraf/lib/network/error'>;
}
declare module 'telegraf/lib/network/multipart-stream.js' {
  declare module.exports: $Exports<'telegraf/lib/network/multipart-stream'>;
}
declare module 'telegraf/lib/network/webhook.js' {
  declare module.exports: $Exports<'telegraf/lib/network/webhook'>;
}
declare module 'telegraf/lib/telegraf.js' {
  declare module.exports: $Exports<'telegraf/lib/telegraf'>;
}
declare module 'telegraf/lib/telegram.js' {
  declare module.exports: $Exports<'telegraf/lib/telegram'>;
}
